# Generated by Django 5.2 on 2025-05-29 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('os', models.CharField()),
                ('command', models.CharField()),
                ('description', models.TextField(blank=True, default='Not provided', null=True)),
                ('syntax', models.CharField(blank=True, default='Not provided')),
                ('parameters', models.CharField(blank=True, default='Not provided')),
                ('examples', models.TextField(blank=True, default=None, null=True)),
                ('source', models.URLField(blank=True, default=None, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
