# Generated by Django 5.2.1 on 2025-06-05 08:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0006_alter_command_examples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='examples',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
