# Generated by Django 5.2.1 on 2025-06-05 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0008_remove_command_parameters_command_parent_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='command',
        ),
        migrations.AddField(
            model_name='command',
            name='parameters',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='command.parameter'),
            preserve_default=False,
        ),
    ]
