# Generated by Django 5.2.1 on 2025-06-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0011_remove_command_parameters_parameter_command'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ('name',)},
        ),
    ]
