# Generated by Django 5.2.1 on 2025-06-05 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("command", "0012_alter_command_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="command",
            name="parent",
        ),
    ]
