# Generated by Django 5.2.1 on 2025-06-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("command", "0013_remove_command_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="command",
            name="syntax",
            field=models.CharField(blank=True, default="Not provided", null=True),
        ),
    ]
