# Generated by Django 5.2.1 on 2025-06-06 12:54

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0014_alter_command_syntax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),
        migrations.AddIndex(
            model_name='command',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='command_com_name_018d06_gin'),
        ),
    ]
