# Generated by Django 5.2.1 on 2025-06-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0015_command_command_com_name_018d06_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='source',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
