# Generated by Django 5.2.1 on 2025-06-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("computer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="computer",
            name="os",
            field=models.CharField(default="Windows"),
        ),
    ]
