# Generated by Django 5.2 on 2025-04-29 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("nickname", models.CharField(max_length=100)),
                ("password", models.CharField()),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="computers", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
