# Generated by Django 5.2 on 2025-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_computer_nickname_room_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='channel_name',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
