# Generated by Django 5.2 on 2025-05-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_computer_channel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='context',
            new_name='text',
        ),
    ]
