# Generated by Django 5.2.1 on 2026-03-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('computer', '0002_computer_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('computers', models.ManyToManyField(related_name='programs', to='computer.computer')),
            ],
        ),
    ]
