# Generated by Django 5.2 on 2025-05-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="channel_name",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
