# Generated by Django 5.2 on 2025-05-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
