# Generated by Django 5.2.1 on 2025-06-07 10:58

import functools
import pathlib
import video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='No provided')),
                ('url', models.URLField()),
                ('preview', models.ImageField(blank=True, null=True, upload_to=functools.partial(video.models.get_file_name, *(), **{'folder_name': pathlib.PureWindowsPath('video_preview')}))),
            ],
        ),
    ]
