# Generated by Django 5.2.1 on 2026-06-22 07:36

import functools
import pathlib
import video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(video.models.get_file_name, *(), **{'folder_name': pathlib.PureWindowsPath('video_preview')})),
        ),
    ]
